<?php

use Drupal\search_api\IndexInterface;

/**
 * React after items were indexed.
 *
 * @param \Drupal\search_api\IndexInterface $index
 *   The used index.
 * @param array $item_ids
 *   An array containing the successfully indexed items' IDs.
 */
function _search_api_elasticsearch_attachments_search_api_items_indexed(IndexInterface $index, array $item_ids) {
  //if ($index->isValidDatasource('entity:file')) {
    //$foo = $index->loadItemsMultiple($item_ids);
//    // Note that this is just an example, and would only work if there are only
//    // nodes indexed in that index (and even then the printed IDs would probably
//    // not be as expected).
//    drupal_set_message(t('Nodes indexed: @ids.', implode(', ', $item_ids)));
    //ksm($foo);
  //}

  //ksm($index);
  //ksm($item_ids);

}